# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on: push

# List of jobs
jobs:
  # Run interaction tests
  # interaction-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Install Playwright
  #       run: npx playwright install --with-deps
  #     - name: Build Storybook
  #       run: yarn build-storybook --quiet
  #     - name: Serve Storybook and run tests
  #       run: |
  #         npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
  #           "npx http-server storybook-static --port 6006 --silent" \
  #           "npx wait-on tcp:6006 && yarn test-storybook"
  visual-tests:
    runs-on: ubuntu-latest
    # The list of steps that the action will go through
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
